---
title: "SBAE_CR1_Comparisons"
output:
  html_document:
    df_print: paged
---

## Environment 

```{r env}
library(waldo)
library(tidyverse)
library(here)
```


### Functions

Function to load and compare objects saved as RDS
```{r func}
# provide paths to rds files
compare_obj <- function(ca_path, cr_path){
  
# generate a list of files to compare based on what was generated by CR  
obj_outs <- list.files(cr_path, pattern = ".rds")

# recursively load and compare objects
for (i in obj_outs) {
  if (file.exists(paste0(cr_path, "/",i))) {
    cat("\n", i, "\n", "\n")
    tmp_CR <- readRDS(paste0(cr_path, "/", i))
    tmp_CA <- readRDS(paste0(ca_path, "/", i))
    print(waldo::compare(tmp_CR, tmp_CA, tolerance = 1e-4))
    cat("\n", "\n", "\n")
 } else {
   cat("\n", i, "\n", "\n")
   # or report that there is not a file
   print(paste0(i, " is not found in independent run output directory "))
   cat("\n", "\n", "\n")
  }
} 
}


compare_delim <- function(ca_path, cr_path, delim = NULL, patt){
  # generate a list of files to compare based on what was generated by CR  
delim_outs <- list.files(cr_path, pattern = patt)

# recursively load and compare delimited output
for (i in delim_outs) {
  if (file.exists(paste0(cr_path, "/",i))) {
    cat("\n", i, "\n", "\n")
    tmp_CR <- readr::read_delim(paste0(cr_path, "/", i), delim = delim, col_names = FALSE)
    tmp_CA <- readr::read_delim(paste0(ca_path, "/", i), delim = delim, col_names = FALSE)
    print(waldo::compare(tmp_CR, tmp_CA, tolerance = 1e-6))
    cat("\n", "\n", "\n")
 } else {
   cat("\n", i, "\n", "\n")
   # or report that there is not a file
   print(paste0(i, " is not found in independent run output directory "))
   cat("\n", "\n", "\n")
  }
} 
}
```

Check data/gtex_qsmooth

```{r gtxqsmooth}

cr_path <- here::here("data", "gtex_qsmooth")

# there were issues with comparing in JF directory - copied directory to CR directory
ca_path <- here::here("data", "gtex_qsmooth_jf") 

compare_obj(ca_path = ca_path, cr_path = cr_path)

```

Check data/panda_input_data

```{r pandainput}
cr_path <- here::here("data", "panda_input_data")
#ca_path <- "/data/project/lasseigne_lab/JLF_scratch/Sex_Bias_Adverse_Events/data/panda_input_data"

ca_path <- here::here("data", "panda_input_data_jf") 
compare_obj(ca_path = ca_path, cr_path = cr_path)
```


Check results/lioness/processed_normalized_expression

```{r lioness}
cr_path <- here::here("results", "ac_results", "lioness", "processed_normalized_expression")
ca_path <- here::here("results", "lioness_jf", "processed_normalized_expression")
compare_obj(ca_path = ca_path, cr_path = cr_path)
```


Check results/alpaca/sex_specific_networks

```{r alpaca, eval=FALSE}
cr_path <- here::here("results", "ac_results", "alpaca", "sex_specific_networks")
ca_path <- here::here("results", "alpaca_jf", "sex_specific_networks")
compare_obj(ca_path = ca_path, cr_path = cr_path)
```
Check results/alpaca/alpaca_adjusted_inputs

```{r}
cr_path <- here::here("results", "ac_results", "alpaca", "alpaca_adjusted_inputs")
ca_path <- here::here("results", "alpaca_jf", "alpaca_adjusted_inputs")
compare_obj(ca_path = ca_path, cr_path = cr_path)
```

Check results/alpaca/alpaca_run

```{r}
cr_path <- here::here("results", "ac_results", "alpaca", "alpaca_run")
ca_path <- here::here("results", "alpaca_jf", "alpaca_run")
compare_delim(ca_path = ca_path, cr_path = cr_path, delim = "\t", patt = ".txt")

```



```{r sinfo}
sessionInfo()
```

